tut::restartable_wrapper Class Reference
tut::restartable_wrapper Class Reference
tut::restartable_wrapper Class Reference
#include <tut_restartable.hpp>
Public Member Functions
restartable_wrapper (const std::string &dir=".")
void erase_callback (callback *cb)
const callbacks & get_callbacks () const
void insert_callback (callback *cb)
groupnames list_groups () const
void register_group (const std::string &name, group_base *gr)
void run_tests () const
void set_callback (callback *cb)
void set_callbacks (const callbacks &cb)
Detailed Description
Restartable test runner wrapper.
Examples:
restartable/main.cpp.
Constructor & Destructor Documentation
tut::restartable_wrapper::restartable_wrapper (const std::string & dir = ".") inline
Default constructor.
Parameters
dir Directory where to search/put log and journal files
Member Function Documentation
groupnames tut::restartable_wrapper::list_groups () const inline
Returns list of known test groups.
References tut::test_runner::list_groups().
Referenced by run_tests().
void tut::restartable_wrapper::register_group (const std::string & name, group_base * gr) inline
Stores another group for getting by name.
References tut::test_runner::register_group().
void tut::restartable_wrapper::run_tests () const inline
Runs all tests in all groups.
References list_groups(), and tut::test_runner::run_test().
void tut::restartable_wrapper::set_callback (callback * cb) inline
Stores callback object.
The documentation for this class was generated from the following file:
tut_restartable.hpp
All Rights Reserved. Generated on Wed Dec 18 2013 11:19:52 for TUT by doxygen 1.8.5