tut::test_group< class, int > Class Template Reference
tut::test_group< class, int > Class Template Reference
tut::test_group< class, int > Class Template Reference
#include <tut.hpp>
Public Types
typedef test_object< Data > object
Public Member Functions
test_group (const char *name)
test_group (const char *name, test_runner &another_runner)
void reg (int n, testmethod tm)
void reset_holder_ (safe_holder< object > &obj)
void rewind ()
bool run_next (test_result &tr)
bool run_test (int n, test_result &tr)
bool run_test_ (const tests_iterator &ti, safe_holder< object > &obj, test_result &tr)
seh_result run_test_seh_ (testmethod tm, safe_holder< object > &obj, std::string &current_test_name, int current_test_id)
Public Member Functions inherited from tut::test_group_posix
template<typename T >
void send_result_ (const T *, const test_result &)
Detailed Description
template<class, int>
class tut::test_group< class, int >
Test group; used to recreate test object instance for each new test since we have to have reinitialized Data base class.
Constructor & Destructor Documentation
template<class , int > tut::test_group< class, int >::test_group (const char * name) inline
Creates and registers test group with specified name.
References tut::test_runner::register_group().
template<class , int > tut::test_group< class, int >::test_group (const char * name, test_runner & another_runner) inline
This constructor is used in self-test run only.
References tut::test_group< class, int >::reg(), and tut::test_runner::register_group().
Member Function Documentation
template<class , int > void tut::test_group< class, int >::reg (int n, testmethod tm) inline
Registers test method under given number.
Referenced by tut::test_group< class, int >::test_group().
template<class , int > void tut::test_group< class, int >::rewind () inline virtual
Reset test position before first test.
Implements tut::group_base.
template<class , int > bool tut::test_group< class, int >::run_next (test_result & tr) inline virtual
Runs next test.
Implements tut::group_base.
References tut::test_group< class, int >::run_test_().
template<class , int > bool tut::test_group< class, int >::run_test (int n, test_result & tr) inline virtual
Runs one test by position.
Implements tut::group_base.
References tut::test_group< class, int >::run_test_().
template<class , int > bool tut::test_group< class, int >::run_test_ (const tests_iterator & ti, safe_holder< object > & obj, test_result & tr) inline
VC allows only one exception handling type per function, so I have to split the method.
References tut::test_result::ex, tut::test_result::message, tut::test_result::name, tut::test_result::ok, and tut::test_group< class, int >::run_test_seh_().
Referenced by tut::test_group< class, int >::run_next(), and tut::test_group< class, int >::run_test().
template<class , int > seh_result tut::test_group< class, int >::run_test_seh_ (testmethod tm, safe_holder< object > & obj, std::string & current_test_name, int current_test_id) inline
Runs one under SEH if platform supports it.
Referenced by tut::test_group< class, int >::run_test_().
The documentation for this class was generated from the following file:
tut.hpp
All Rights Reserved. Generated on Wed Dec 18 2013 11:19:52 for TUT by doxygen 1.8.5